sudo: required
services:
  - docker


before_install:
  - docker image pull devianspade/alpine-flask

script:
  - docker container run -p 5000:5000 -d --name alflask devianspade/alpine-flask

deploy:
  provider: "elasticbeanstalk"
  region: "us-east-2"
  app: "alflask001"
  env: "Alflask001-env"
  bucketname: "elasticbeanstalk-us-east-2-417856445387"
  bucketpath: "alflask001"
  on:
    branch: "master"
  access_key_id: $access_key_id
  secret_access_key:
    secure: $access_key_secret




